# Business Intelligence & Data Engineering
---
**MSc in Business Analytics** | *Athens University of Economics and Business* **Assignment:** Apache Spark  
**Student:** Anastasios Rigos (f2822511)

Apache Spark run on Java 17 or Java 21, we will use Java 21.

In [13]:
import os

JAVA_HOME = "/opt/homebrew/Cellar/openjdk@21/21.0.10/libexec/openjdk.jdk/Contents/Home"
os.environ["JAVA_HOME"] = JAVA_HOME

In [14]:
! echo $JAVA_HOME

/opt/homebrew/Cellar/openjdk@21/21.0.10/libexec/openjdk.jdk/Contents/Home

In [15]:
! java -version

openjdk version "21.0.10" 2026-01-20
OpenJDK Runtime Environment Homebrew (build 21.0.10)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.10, mixed mode, sharing)

# Part 1 - SparkSQL

We set up the scene by importing from the class SparkSession from the library pyspark

In [16]:
from pyspark.sql import SparkSession

We create a Spark Session for the Q-Commerce project with Application Name "Q-Commerce-project".

In [17]:
spark = SparkSession.builder.appName("Q-Commerce-project").getOrCreate()

We read the retail-dataset.csv file in the folder ./data and we save it in a dataframe with the name retail_df.

In [18]:
# header=True: the first row of the CSV file contains the column names
# inferSchema=True: automatically infer the data types of the columns
retail_df = spark.read.csv("data/retail-dataset.csv", header=True, inferSchema=True)

## Question 1: Display descriptive statistics for each column of the dataset.  

We display the descriptive statistics for each column of the dataset using the describe() method in pandas, which provides us the count, the meand, the standard deviation, the minimum and the maximum value of each column.

In [19]:
retail_df.describe().toPandas()

,summary,Transaction_ID,Customer_Name,Product,Total_Items,Total_Cost,Payment_Method,City,Store_Type,Customer_Category,Season,Promotion
0,count,1000000,1000000,1000000,1000000,1000000,1000000,1000000,1000000,1000000,1000000,1000000
1,mean,1.0004999995E9,NaN,NaN,5.495941,52.455220400000094,NaN,NaN,NaN,NaN,NaN,NaN
2,stddev,288675.2789323441,NaN,NaN,2.871654187209314,27.41698914533317,NaN,NaN,NaN,NaN,NaN,NaN
3,min,1000000000,Aaron Acevedo,"['Air Freshener', 'Air Freshener', 'Air Freshe...",1,5.0,Cash,Atlanta,Convenience Store,Homemaker,Fall,BOGO (Buy One Get One)
4,max,1000999999,Zoe York,['Yogurt'],10,100.0,Mobile Payment,Seattle,Warehouse Club,Young Adult,Winter,None

Alternatively, we can use the summary() method, which provide also the 25%, 50%, 75% quartiles for the numeric variables

In [20]:
retail_df.summary().toPandas()

,summary,Transaction_ID,Customer_Name,Product,Total_Items,Total_Cost,Payment_Method,City,Store_Type,Customer_Category,Season,Promotion
0,count,1000000,1000000,1000000,1000000,1000000,1000000,1000000,1000000,1000000,1000000,1000000
1,mean,1.0004999995E9,NaN,NaN,5.495941,52.455220400000094,NaN,NaN,NaN,NaN,NaN,NaN
2,stddev,288675.2789323441,NaN,NaN,2.871654187209314,27.41698914533317,NaN,NaN,NaN,NaN,NaN,NaN
3,min,1000000000,Aaron Acevedo,"['Air Freshener', 'Air Freshener', 'Air Freshe...",1,5.0,Cash,Atlanta,Convenience Store,Homemaker,Fall,BOGO (Buy One Get One)
4,25%,1000249917,NaN,NaN,3,28.71,NaN,NaN,NaN,NaN,NaN,NaN
5,50%,1000500057,NaN,NaN,5,52.42,NaN,NaN,NaN,NaN,NaN,NaN
6,75%,1000749990,NaN,NaN,8,76.18,NaN,NaN,NaN,NaN,NaN,NaN
7,max,1000999999,Zoe York,['Yogurt'],10,100.0,Mobile Payment,Seattle,Warehouse Club,Young Adult,Winter,None

As we can see the dataset contains 1,000,000 rows of transcations. The numeric columns consist of Transaction_ID, Total_Items and Total_Cost and the categorical ones are Customer_Name, Product

## Question 2. Identify the customers that pay in cash and display the two corresponding columns.  

Let's see which are the types of the Payment Method.

In [ ]:
# Select distinct values from the Payment_Method column and convert the result to a Pandas DataFrame
retail_df.select("Payment_Method").distinct().toPandas()

   Payment_Method
0  Mobile Payment
1     Credit Card
2            Cash
3      Debit Card

We see that that the Payment Method for paying in cash is "Cash".  
So we want to find the transactions that the customer paid with cash and display only the two corresponding columns.

In [ ]:
# Filter the DataFrame to include only rows where the Payment_Method is 'Cash',
# select only the Customer_Name and Payment_Method columns 
# and convert the resulting DataFrame to a Pandas DataFrame
retail_df.filter("Payment_Method == 'Cash'") \
    .select("Customer_Name", "Payment_Method") \
    .toPandas()

           Customer_Name Payment_Method
0       Michelle Carlson           Cash
1         Joshua Frazier           Cash
2       Victoria Garrett           Cash
3           Angela Jones           Cash
4             Don Harris           Cash
...                  ...            ...
250225      Joshua Green           Cash
250226    Leslie Sanford           Cash
250227       Gary Mosley           Cash
250228    James Villegas           Cash
250229      Emily Graham           Cash

[250230 rows x 2 columns]

We have 250230 transactions, where customers paid in cash with their corresponding names.

In [23]:
#spark.stop()